#!/usr/bin/env python3
"""
================================================================================
🏛️ BAYESIAN PIVOT TRADING INFRASTRUCTURE // TIER 5 PIPELINE INVARIANTS
================================================================================
Master Integration & Signal-to-Order Handshake Invariants.
Guarantees that:
1. Active symbols and strategy graduation configs are 100% coherent.
2. Strategy 5 Gold Longs qualify for live execution in Asian, London, and NY sessions.
3. Every scanner pattern type is authorized in AIPermissionMap with positive risk multiplier.
4. Gold order sizing, contract sizing, and firewall audits pass without silent interception.
"""

import unittest
from datetime import datetime, timezone
import pandas as pd
import numpy as np

from src.core.config import Config
from src.engines.ai_permission_map import AIPermissionMap
from src.core.execution_firewall import ExecutionFirewall
from src.engines.alpha_sweep_scanner import AlphaSweepScanner


class TestPipelineE2EInvariants(unittest.TestCase):

    def test_config_coherence_gold_live(self):
        """Invariant: Graduated strategies must not have their target symbols trapped in shadow quarantine."""
        self.assertIn("XAU/USD", Config.SYMBOLS, "XAU/USD must be in Config.SYMBOLS for live fleet execution.")
        self.assertNotIn("XAU/USD", Config.SHADOW_SYMBOLS, "XAU/USD must not be trapped in Config.SHADOW_SYMBOLS.")
        self.assertTrue(getattr(Config, "STRATEGY_5_AUTO_EXECUTE", False), "STRATEGY_5_AUTO_EXECUTE must be True.")
        self.assertTrue(getattr(Config, "LIVE_AUTO_EXECUTION", False), "LIVE_AUTO_EXECUTION must be True.")
        self.assertLessEqual(getattr(Config, "AUTO_EXECUTION_MIN_SCORE", 8.5), 8.0, "AUTO_EXECUTION_MIN_SCORE must be <= 8.0.")

    def test_strategy_5_gold_asian_session_live_qualification(self):
        """Invariant: Strategy 5 Gold Longs must qualify for live execution during Asian Session Judas sweeps."""
        scanner = AlphaSweepScanner.__new__(AlphaSweepScanner)
        
        # Construct synthetic 1H data with a bullish FVG
        now = datetime.now(timezone.utc)
        dates_1h = pd.date_range(end=now, periods=10, freq="1h")
        df_1h = pd.DataFrame({
            "timestamp": dates_1h,
            "open": [4300 + i * 5 for i in range(10)],
            "high": [4310 + i * 5 for i in range(10)],
            "low": [4295 + i * 5 for i in range(10)],
            "close": [4305 + i * 5 for i in range(10)],
            "volume": [1000] * 10
        })
        # Inject Bullish FVG between index 6 and 8
        c1_high = 4330.0
        c3_low = 4340.0
        df_1h.loc[6, "high"] = c1_high
        df_1h.loc[6, "low"] = 4320.0
        df_1h.loc[8, "low"] = c3_low
        df_1h.loc[8, "high"] = 4350.0
        df_1h.loc[9, "close"] = 4345.0  # Above EMA

        ce_level = (c1_high + c3_low) / 2.0  # 4335.0

        # Construct synthetic 5m data where price tapped CE level and closed above it
        dates_5m = pd.date_range(end=now, periods=10, freq="5min")
        df_5m = pd.DataFrame({
            "timestamp": dates_5m,
            "open": [4337.0] * 10,
            "high": [4339.0] * 10,
            "low": [4334.0] * 10,  # Below CE (4335.0)
            "close": [4336.5] * 10,  # Closed above CE
            "volume": [500] * 10
        })

        # Evaluate inside ASIAN_SESSION_JUDAS on a weekday
        setup = scanner.check_fvg_50pct_ce_midpoint_shadow(
            symbol="XAU/USD",
            df_5m=df_5m,
            df_1h=df_1h,
            killzone="ASIAN_SESSION_JUDAS"
        )

        self.assertIsNotNone(setup, "Strategy 5 setup should be detected for Gold FVG CE tap.")
        self.assertEqual(setup["direction"], "LONG")
        self.assertEqual(setup["pattern_type"], "STRAT_5_XAU_GOLD_50PCT_CE_LONG")
        self.assertFalse(setup["is_shadow_only"], "Strategy 5 Gold Long in Asian session must be live-qualified (not shadow).")
        self.assertGreater(setup["take_profit"], setup["price"], "Take profit must be above entry price for longs.")
        self.assertLess(setup["stop_loss"], setup["price"], "Stop loss must be below entry price for longs.")

    def test_archetype_parity_across_all_active_strategies(self):
        """Invariant: Every pattern type generated by AlphaSweepScanner must be authorized in AIPermissionMap."""
        active_patterns = [
            ("BTC/USD", "LONG", "JUDAS_INDUCEMENT_SNIPER"),
            ("BTC/USD", "SHORT", "JUDAS_INDUCEMENT_SNIPER"),
            ("BTC/USD", "LONG", "TURTLE_SOUP_LIQUIDITY_SWEEP"),
            ("BTC/USD", "SHORT", "TURTLE_SOUP_LIQUIDITY_SWEEP"),
            ("BTC/USD", "LONG", "LONDON_CLOSE_SILVER_BULLET"),
            ("BTC/USD", "SHORT", "LONDON_CLOSE_SILVER_BULLET"),
            ("XAU/USD", "LONG", "STRAT_5_XAU_GOLD_50PCT_CE_LONG"),
            ("XAU/USD", "LONG", "FVG_50PCT_CE_REVERSAL_LONG"),
            ("XAU/USD", "LONG", "FVG_50PCT_CE_REVERSAL"),
            ("XAU/USD", "LONG", "FVG_CONSEQUENT_ENCROACHMENT"),
            ("XAU/USD", "LONG", "FVG_50PCT_CE_REVERSAL_SHADOW"),
        ]

        for sym, direction, pattern in active_patterns:
            is_permitted, risk_mult, reason = AIPermissionMap.evaluate_confluence(sym, direction, pattern)
            self.assertTrue(
                is_permitted,
                f"Pattern {pattern} for {sym} {direction} must be permitted in AIPermissionMap. Reason: {reason}"
            )
            self.assertGreater(
                risk_mult, 0.0,
                f"Pattern {pattern} must have positive risk multiplier (got {risk_mult}x)."
            )

    def test_firewall_approves_gold_high_conviction(self):
        """Invariant: ExecutionFirewall must approve a valid Gold Long with AI Score >= 8.0."""
        is_approved, reason = ExecutionFirewall.audit_trade_request(
            symbol="XAU/USD",
            side="buy",
            stop_loss=4340.0,
            take_profit=4360.0,
            ai_score=8.0,
            is_htf_confirmed=True,
            bypass_weekend=True,
            bypass_cooldown=True,
            bypass_killzone=True,
            bypass_circuit_breaker=True
        )
        self.assertTrue(is_approved, f"ExecutionFirewall should approve Gold Long. Blocked reason: {reason}")

    def test_gold_contract_size_and_pricing_parity(self):
        """Invariant: Contract size must be 100.0 for Gold (XAU/USD) and 1.0 for BTC."""
        self.assertEqual(Config.get_contract_size("XAU/USD"), 100.0)
        self.assertEqual(Config.get_contract_size("BTC/USD"), 1.0)
        self.assertEqual(Config.get_contract_size("ETH/USD"), 1.0)
        self.assertEqual(Config.get_contract_size("XAG/USD"), 5000.0)

    def test_metals_intermarket_relative_strength_leader_invariant(self):
        """Invariant: Metals relative strength engine accurately identifies XAU_LEADER vs XAG_LEADER."""
        scanner = AlphaSweepScanner.__new__(AlphaSweepScanner)
        
        # Test 1: XAU outperforming XAG -> XAU_LEADER
        dates = pd.date_range("2026-09-28", periods=25, freq="1h")
        df_xau_lead = pd.DataFrame({"close": np.linspace(4000, 4400, 25)}, index=dates)
        df_xag_lag = pd.DataFrame({"close": np.linspace(65, 60, 25)}, index=dates)
        
        scanner.fetch_data = lambda sym, tf, limit=30, synchronized=False: df_xau_lead if "XAU" in sym else df_xag_lag
        leader = scanner.get_metals_relative_strength_leader()
        self.assertEqual(leader, "XAU_LEADER")

        # Test 2: XAG outperforming XAU -> XAG_LEADER
        df_xau_lag = pd.DataFrame({"close": np.linspace(4400, 4000, 25)}, index=dates)
        df_xag_lead = pd.DataFrame({"close": np.linspace(60, 75, 25)}, index=dates)
        scanner.fetch_data = lambda sym, tf, limit=30, synchronized=False: df_xau_lag if "XAU" in sym else df_xag_lead
        leader = scanner.get_metals_relative_strength_leader()
        self.assertEqual(leader, "XAG_LEADER")


if __name__ == "__main__":
    unittest.main()
